name: Run a notebook in databricks on PRs

on:
 pull_request:

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Setup python
       uses: actions/setup-python@v4
       with:
          python-version: '3.9'
     - name: Configure python pacakges
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli --upgrade
     - name: Run deployment workflow on databricks
       run: |
         pip install numpy
         pip install pyspark
         pip install matplotlib
         pip install mlflow
         python databricks-notebooks/Train_eval_register.py
         with:
           DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
           DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
           new-cluster-json: >
             {
               "num_workers": 1,
               "spark_version": "12.0.x-cpu-ml-scala2.12",
               "node_type_id": "Standard_DS3_v2"
             }