name: Run a notebook in databricks on PRs

on:
 pull_request:

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Setup python
       uses: actions/setup-python@v4
       with:
          python-version: '3.9'
     - name: Configure python pacakges
       run: |
          python -m pip install --upgrade pip
          pip install databricks-cli --upgrade
     - name: Trigger test file as an experiment
       run: |
          pip install pyspark
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          python NYC_taxi_table.py