name: Run a notebook in databricks on PRs

on:
 push:

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   environment: Dev
   steps:
     - name: Checkout repo
       uses: actions/checkout@v3
     - name: Setup python
       uses: actions/setup-python@v2
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: Using MLflow to Track Experiments
         databricks-host: ${{ secrets.DATABRICKS_HOST }}
         databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "12.0.x-cpu-ml-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }