name: Run a notebook in databricks on PRs

on:
 pull_request:

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v3
     - name: Setup python
       uses: actions/setup-python@v2
     - name: Configure python packages
       run: |
          python -m pip install --upgrade pip
          pip install databricks-cli --upgrade
     - name: Run deployment workflow on databricks
       run: |
         export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
         export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
         python databricks-notebooks/Using MLflow to Track Experiments.py
         with:
           new-cluster-json: >
             {
               "num_workers": 1,
               "spark_version": "12.0.x-cpu-ml-scala2.12",
               "node_type_id": "Standard_DS3_v2"
             }