name: Move the model to staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch.
  push:
    branches: [Staging]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # job 1: "build" -- trains a new model an ensures that it meets some threshold for performance
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure python packages
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli --upgrade
          
      - name: Run training on databricks
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          python databricks-triggers/test.py
          python databricks-triggers/stage.py 
          
      